library("devtools", lib.loc="/Library/Frameworks/R.framework/Versions/3.1/Resources/library")
library("knitr", lib.loc="/Library/Frameworks/R.framework/Versions/3.1/Resources/library")
library("DBI", lib.loc="/Library/Frameworks/R.framework/Versions/3.1/Resources/library")
library("ggplot2", lib.loc="/Library/Frameworks/R.framework/Versions/3.1/Resources/library")
library("rJava", lib.loc="/Library/Frameworks/R.framework/Versions/3.1/Resources/library")
library("RJDBC", lib.loc="/Library/Frameworks/R.framework/Versions/3.1/Resources/library")
library("shiny", lib.loc="/Library/Frameworks/R.framework/Versions/3.1/Resources/library")
library("maps", lib.loc="/Library/Frameworks/R.framework/Versions/3.1/Resources/library")
library("mapproj", lib.loc="/Library/Frameworks/R.framework/Versions/3.1/Resources/library")
library("shinyapps")
